// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $admin_currencyManagement from "./routes/admin/currencyManagement.tsx";
import * as $admin_regionManagement from "./routes/admin/regionManagement.tsx";
import * as $admin_userManagement from "./routes/admin/userManagement.tsx";
import * as $api_currency from "./routes/api/currency.ts";
import * as $api_database from "./routes/api/database.ts";
import * as $api_infra from "./routes/api/infra.ts";
import * as $api_infraFamily from "./routes/api/infraFamily.ts";
import * as $api_infraInstance from "./routes/api/infraInstance.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_project from "./routes/api/project.ts";
import * as $api_region from "./routes/api/region.ts";
import * as $api_statsInfra from "./routes/api/statsInfra.ts";
import * as $api_user from "./routes/api/user.ts";
import * as $app_container from "./routes/app/container.tsx";
import * as $app_database from "./routes/app/database.tsx";
import * as $app_infra from "./routes/app/infra.tsx";
import * as $app_project from "./routes/app/project.tsx";
import * as $app_statsInfra from "./routes/app/statsInfra.tsx";
import * as $app_statsRegion from "./routes/app/statsRegion.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $index from "./routes/index.tsx";
import * as $login_layout from "./routes/login/_layout.tsx";
import * as $login_index from "./routes/login/index.tsx";
import * as $login_login from "./routes/login/login.tsx";
import * as $login_logout from "./routes/login/logout.tsx";
import * as $login_register from "./routes/login/register.tsx";
import * as $menu from "./routes/menu.tsx";
import * as $Badge from "./islands/Badge.tsx";
import * as $LogoutButton from "./islands/LogoutButton.tsx";
import * as $Register from "./islands/Register.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import * as $admin_CurrencyManagement from "./islands/admin/CurrencyManagement.tsx";
import * as $admin_CurrencyUpdateButton from "./islands/admin/CurrencyUpdateButton.tsx";
import * as $admin_RegionManagement from "./islands/admin/RegionManagement.tsx";
import * as $admin_RegionSelectButtons from "./islands/admin/RegionSelectButtons.tsx";
import * as $admin_UserManagement from "./islands/admin/UserManagement.tsx";
import * as $app_InfraFamilyInfo from "./islands/app/InfraFamilyInfo.tsx";
import * as $app_InfraInstanceInfo from "./islands/app/InfraInstanceInfo.tsx";
import * as $app_InfraResultsChart from "./islands/app/InfraResultsChart.tsx";
import * as $app_ProjectManagement from "./islands/app/ProjectManagement.tsx";
import * as $app_ProjectSelectButtons from "./islands/app/ProjectSelectButtons.tsx";
import * as $app_ProviderSelectButtons from "./islands/app/ProviderSelectButtons.tsx";
import * as $app_SaveProject from "./islands/app/SaveProject.tsx";
import * as $app_StatsInfraChartByFamily from "./islands/app/StatsInfraChartByFamily.tsx";
import * as $app_StatsInfraChartByRegion from "./islands/app/StatsInfraChartByRegion.tsx";
import * as $app_StatsSelectRegion from "./islands/app/StatsSelectRegion.tsx";
import * as $chart from "./islands/chart.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/admin/currencyManagement.tsx": $admin_currencyManagement,
    "./routes/admin/regionManagement.tsx": $admin_regionManagement,
    "./routes/admin/userManagement.tsx": $admin_userManagement,
    "./routes/api/currency.ts": $api_currency,
    "./routes/api/database.ts": $api_database,
    "./routes/api/infra.ts": $api_infra,
    "./routes/api/infraFamily.ts": $api_infraFamily,
    "./routes/api/infraInstance.ts": $api_infraInstance,
    "./routes/api/login.ts": $api_login,
    "./routes/api/project.ts": $api_project,
    "./routes/api/region.ts": $api_region,
    "./routes/api/statsInfra.ts": $api_statsInfra,
    "./routes/api/user.ts": $api_user,
    "./routes/app/container.tsx": $app_container,
    "./routes/app/database.tsx": $app_database,
    "./routes/app/infra.tsx": $app_infra,
    "./routes/app/project.tsx": $app_project,
    "./routes/app/statsInfra.tsx": $app_statsInfra,
    "./routes/app/statsRegion.tsx": $app_statsRegion,
    "./routes/contact.tsx": $contact,
    "./routes/index.tsx": $index,
    "./routes/login/_layout.tsx": $login_layout,
    "./routes/login/index.tsx": $login_index,
    "./routes/login/login.tsx": $login_login,
    "./routes/login/logout.tsx": $login_logout,
    "./routes/login/register.tsx": $login_register,
    "./routes/menu.tsx": $menu,
  },
  islands: {
    "./islands/Badge.tsx": $Badge,
    "./islands/LogoutButton.tsx": $LogoutButton,
    "./islands/Register.tsx": $Register,
    "./islands/Sidebar.tsx": $Sidebar,
    "./islands/admin/CurrencyManagement.tsx": $admin_CurrencyManagement,
    "./islands/admin/CurrencyUpdateButton.tsx": $admin_CurrencyUpdateButton,
    "./islands/admin/RegionManagement.tsx": $admin_RegionManagement,
    "./islands/admin/RegionSelectButtons.tsx": $admin_RegionSelectButtons,
    "./islands/admin/UserManagement.tsx": $admin_UserManagement,
    "./islands/app/InfraFamilyInfo.tsx": $app_InfraFamilyInfo,
    "./islands/app/InfraInstanceInfo.tsx": $app_InfraInstanceInfo,
    "./islands/app/InfraResultsChart.tsx": $app_InfraResultsChart,
    "./islands/app/ProjectManagement.tsx": $app_ProjectManagement,
    "./islands/app/ProjectSelectButtons.tsx": $app_ProjectSelectButtons,
    "./islands/app/ProviderSelectButtons.tsx": $app_ProviderSelectButtons,
    "./islands/app/SaveProject.tsx": $app_SaveProject,
    "./islands/app/StatsInfraChartByFamily.tsx": $app_StatsInfraChartByFamily,
    "./islands/app/StatsInfraChartByRegion.tsx": $app_StatsInfraChartByRegion,
    "./islands/app/StatsSelectRegion.tsx": $app_StatsSelectRegion,
    "./islands/chart.tsx": $chart,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
